In [19]:
import numpy as np
import pandas as pd
import random
from IPython import display
from collections import namedtuple, deque
import time
from tqdm import tqdm
import matplotlib.pyplot as plt
%matplotlib inline


import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
device = torch.device("cpu")
# use cpu run
import gym

In [20]:
env_args = {
    'run_dssat_location': '/opt/dssat_pdi/run_dssat',  # assuming (modified) DSSAT has been installed in /opt/dssat_pdi
    'log_saving_path': './logs/dssat-pdi.log',  # if you want to save DSSAT outputs for inspection
    # 'mode': 'irrigation',  # you can choose one of those 3 modes
    # 'mode': 'fertilization',
    'mode': 'all',
    'seed': 123456,
    'random_weather': False,  # if you want stochastic weather
    #'fileX_template_path':'./IUAF9901.MZX',
    #'fileX_template_path':'./SIAZ9501.MZX',
    #'experiment_number':1
}
env = gym.make('gym_dssat_pdi:GymDssatPdi-v0', **env_args)
print('Observation:',env.observation,)
print(len(env.observation),len(env.observation['sw']))
ram_dimensions = len(env.observation)+len(env.observation['sw'])-1
nb_actions = 5
print('\nRam information received from DASSAT will has %d dimensions.' % ram_dimensions)
print('There are %d possible actions at each step.' % nb_actions)
print('Discrete?',type(gym.spaces)== gym.spaces.Discrete)
print(ram_dimensions)
# observation has 27 elements, 9 values in soil water
# state size = 27+8 dimension
# how to defind nb_action? why is 200?

Observation: {'cleach': 0.0, 'cnox': 0.0, 'cumsumfert': 0.0, 'dap': 0, 'dtt': 0.0, 'es': 0.0, 'grnwt': 0.0, 'istage': 7, 'nstres': 0.0, 'pcngrn': 0.0, 'pltpop': 7.199999809265137, 'rain': 0.0, 'rtdep': 0.0, 'runoff': 0.0, 'srad': 13.300000190734863, 'sw': array([0.086     , 0.086     , 0.086     , 0.086     , 0.086     ,
       0.076     , 0.076     , 0.13      , 0.25799999]), 'swfac': 0.0, 'tleachd': 0.0, 'tmax': 22.200000762939453, 'tmin': 3.299999952316284, 'tnoxd': 0.0, 'topwt': 0.0, 'trnu': 0.0, 'vstage': 0.0, 'wtdep': 0.0, 'wtnup': 0.0, 'xlai': 0.0}
27 9

Ram information received from DASSAT will has 35 dimensions.
There are 5 possible actions at each step.
Discrete? False
35


In [37]:
env.reset()
i=1
print('day ',i)
print(env.observation)
while not env.done:
    action = {
                    'anfer': 0,  # if mode == fertilization or mode == all ; nitrogen to fertilize in kg/ha4
                    'amir': 10,  # if mode == irrigation or mode == all ; water to irrigate in L/ha
            }
    observation, reward, done, info = env.step(action)
    i=i+1
    print('day ',i)
    #print('action is ', action['anfer'], action['amir'])

    #print(env.observation['dtt'])
    #print((env.observation['tmax']+env.observation['tmin'])/2-8)
#     if env.observation['rain']!= 0:
#         rain.append(env.observation['rain'])
    #print(env.observation['rain'])
    print(env.observation['xlai'])
    #print((env.observation['tmax']+env.observation['tmax'])/2-env.observation['dtt'])
    print('')
print('day ',i+1)
#plt.plot(rain)
#print((env.observation['Tmax']+env.observation['Tmax']/2))


day  1
{'cleach': 0.0, 'cnox': 0.0, 'cumsumfert': 0.0, 'dap': 0, 'dtt': 0.0, 'es': 0.0, 'grnwt': 0.0, 'istage': 7, 'nstres': 0.0, 'pcngrn': 0.0, 'pltpop': 7.199999809265137, 'rain': 0.0, 'rtdep': 0.0, 'runoff': 0.0, 'srad': 13.300000190734863, 'sw': array([0.086     , 0.086     , 0.086     , 0.086     , 0.086     ,
       0.076     , 0.076     , 0.13      , 0.25799999]), 'swfac': 0.0, 'tleachd': 0.0, 'tmax': 22.200000762939453, 'tmin': 3.299999952316284, 'tnoxd': 0.0, 'topwt': 0.0, 'trnu': 0.0, 'vstage': 0.0, 'wtdep': 0.0, 'wtnup': 0.0, 'xlai': 0.0}
day  2
0.0

day  3
0.0

day  4
0.0

day  5
0.0

day  6
0.0

day  7
0.0

day  8
0.0

day  9
0.0

day  10
0.0

day  11
0.0

day  12
0.0

day  13
0.0

day  14
0.0

day  15
0.0

day  16
0.0

day  17
0.0

day  18
0.0

day  19
0.0

day  20
0.0

day  21
0.0

day  22
0.0

day  23
0.0

day  24
0.0

day  25
0.0

day  26
0.0

day  27
0.0

day  28
0.0

day  29
0.0

day  30
0.0

day  31
0.0

day  32
0.0

day  33
0.0

day  34
0.0

day  35
0.0

day  36
0.

In [28]:
import matplotlib.pyplot as plt
env.reset()
i=1
print('day ',i)
print(env.observation)
rain=[]
while not env.done:
    action = {
                    'anfer': 0,  # if mode == fertilization or mode == all ; nitrogen to fertilize in kg/ha4
                    'amir': 10,  # if mode == irrigation or mode == all ; water to irrigate in L/ha
            }
    observation, reward, done, info = env.step(action)
    i=i+1
    print('day ',i)
    #print('action is ', action['anfer'], action['amir'])

    #print(env.observation['dtt'])
    #print((env.observation['tmax']+env.observation['tmin'])/2-8)
#     if env.observation['rain']!= 0:
#         rain.append(env.observation['rain'])
    #print(env.observation['rain'])
    print('')
    rain.append(env.observation['rain'])
print('day ',i+1)
print(rain)
count=0
for i in range(len(rain)):
    if rain[i]>5:
        count=count+1
print(count)
#plt.plot(rain)
#print((env.observation['Tmax']+env.observation['Tmax']/2))



day  1
{'cleach': 0.0, 'cnox': 0.0, 'cumsumfert': 0.0, 'dap': 0, 'dtt': 0.0, 'es': 0.0, 'grnwt': 0.0, 'istage': 7, 'nstres': 0.0, 'pcngrn': 0.0, 'pltpop': 7.199999809265137, 'rain': 0.0, 'rtdep': 0.0, 'runoff': 0.0, 'srad': 13.300000190734863, 'sw': array([0.086     , 0.086     , 0.086     , 0.086     , 0.086     ,
       0.076     , 0.076     , 0.13      , 0.25799999]), 'swfac': 0.0, 'tleachd': 0.0, 'tmax': 22.200000762939453, 'tmin': 3.299999952316284, 'tnoxd': 0.0, 'topwt': 0.0, 'trnu': 0.0, 'vstage': 0.0, 'wtdep': 0.0, 'wtnup': 0.0, 'xlai': 0.0}
day  2

day  3

day  4

day  5

day  6

day  7

day  8

day  9

day  10

day  11

day  12

day  13

day  14

day  15

day  16

day  17

day  18

day  19

day  20

day  21

day  22

day  23

day  24

day  25

day  26

day  27

day  28

day  29

day  30

day  31

day  32

day  33

day  34

day  35

day  36

day  37

day  38

day  39

day  40

day  41

day  42

day  43

day  44

day  45

day  46

day  47

day  48

day  49

day  50

day  51

da

In [5]:
{'cleach': 0.10799805819988251, 'cnox': 0.09022612869739532, 'cumsumfert': 0.0, 'dap': 156, 'dtt': 3.348587989807129, 'es': 0.4543667733669281, 'grnwt': 1971.1811104964727, 'istage': 10, 'nstres': 0.05167698860168457, 'pcngrn': 0.01019499659538269, 'pltpop': 4.699999809265137, 'rain': 0.0, 'rtdep': 152.00247192382812, 'runoff': 0.0, 'srad': 7.400000095367432, 'sw': array([0.084715  , 0.226932  , 0.249892  , 0.26022699, 0.257247  ,
       0.2138    , 0.145355  , 0.178409  , 0.162572  , 0.182973  ,
       0.194765  ]), 'swfac': 0.0, 'tleachd': 0.0, 'tmax': 16.5, 'tmin': 4.599999904632568, 'tnoxd': 0.0, 'topwt': 541.6163940429688, 'trnu': 0.15839403387910123, 'vstage': 20.0, 'wtdep': 152.00294494628906, 'wtnup': 66.37974262237549, 'xlai': 0.0}

NameError: name 'array' is not defined

In [ ]:
Action_list=[]
Nleach_list = []
Yield_list=[]
reward_list=[]
rain_list=[]
for i in range(1):
    #print('')
    rain=0
    env.reset()
    rain=rain+env.observation['rain']
    #print(env.observation)
    #date = 1
    #print(date)
    count = 1
    while not env.done:
        #print(observation)
        #print(observation)
        # observation_list = env.observation_dict_to_array(observation)
        print(env.observation['dap'])
        print('vstage is',env.observation['vstage'])
        print('istage is', env.observation['istage'])
        print('')
        rain=rain+env.observation['rain']
        if env.observation['vstage'] == 5 and count == 1:
                action1 = 1
                count = count -1
        else:
            action1 = 0
        action = {
                    'anfer': action1*360,  # if mode == fertilization or mode == all ; nitrogen to fertilize in kg/ha4
                    'amir': 0,  # if mode == irrigation or mode == all ; water to irrigate in L/ha
            }
        #print(date)
        observation, reward, done, info = env.step(action)
        #print(observation['yrdoy'])
        
        #print('')
        #print(observation)
        #real_ob = add_fert(observation, action_dict['anfer'])
        #print('real_ob is ', real_ob)
        #env.observation = real_ob
        #print('final ob is:', env.observation)
        #real_s=get_real_state(env._state, action_dict['anfer'])
        #env._state=real_s
        #print('env_state', env._state)
        #print(date)
        #print(reward)
        #print(done)
        if done:
            final_ob=env.observation
            #print(final_ob)
            action=final_ob['cumsumfert']
            Nleach=final_ob['cleach']
            Yield=final_ob['topwt']*10
            Action_list.append(action)
            Nleach_list.append(Nleach)
            Yield_list.append(Yield)
            reward=Yield*0.1-0.1*Nleach-0.1*action
            reward_list.append(reward)
            rain_list.append(rain)
            #print(env.history['action'])
            #print(env.history['reward'])
#print(np.mean(rain_list))
#print('N amount is', Action_list)
#print('avergae N input is', np.mean(Action_list))
#print('')
#print('N leaching is', Nleach_list)
#print('avergae Leaching is', np.mean(Nleach_list))
#print('')
#print('Yield is', Yield_list)
#print('avergae Yield is', np.mean(Yield_list))
#print('')
#print('Reward is', reward_list)
#print('avergae reward is', np.mean(reward_list))

In [6]:
env.reset()
print(env.observation)

{'cleach': 0.0, 'cnox': 0.0, 'cumsumfert': 0.0, 'dap': 0, 'dtt': 0.0, 'es': 0.0, 'grnwt': 0.0, 'istage': 7, 'nstres': 0.0, 'pcngrn': 0.0, 'pltpop': 8.0, 'rain': 1.2000000476837158, 'rtdep': 0.0, 'runoff': 0.0, 'srad': 19.799999237060547, 'sw': array([0.20299999, 0.20299999, 0.20299999, 0.28200001, 0.28200001,
       0.223     , 0.223     ]), 'swfac': 0.0, 'tleachd': 0.0, 'tmax': 24.600000381469727, 'tmin': 12.199999809265137, 'tnoxd': 0.0, 'topwt': 0.0, 'trnu': 0.0, 'vstage': 0.0, 'wtdep': 0.0, 'wtnup': 0.0, 'xlai': 0.0}


In [7]:
Nleach_list

NameError: name 'Nleach_list' is not defined

In [8]:
Yield_list

[9600.956420898438,
 4562.802429199219,
 5943.7042236328125,
 9623.003540039062,
 13368.8037109375,
 12950.1904296875,
 9539.637451171875,
 13334.02099609375,
 4795.851135253906,
 10534.593505859375]

In [9]:
reward_list

[942.2311254501343,
 440.038681936264,
 572.0489852905273,
 945.7836225986481,
 1316.0961780548096,
 1276.2494220733643,
 937.7455790758133,
 1314.9191820144654,
 457.27873306274415,
 1036.522788619995]

In [ ]:
b=a[2]

In [9]:
i=1

In [11]:
str(i)+'happy.csv'

'1happy.csv'

In [4]:
penalty = -200

In [5]:
penalty = max(penalty,-100)

In [6]:
penalty

-100

In [29]:
import deepdish as dd
fix_memory = dd.io.load('fix_memory.h5')

In [30]:
import random
e=random.sample(fix_memory,10)
print(e[1])

(array([2.39033165e+01, 8.47997069e-02, 4.00000000e+01, 4.90000000e+01,
       1.62000008e+01, 2.24891400e+00, 0.00000000e+00, 3.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 7.19999981e+00, 0.00000000e+00,
       6.41389465e+01, 0.00000000e+00, 2.07000008e+01, 4.70849983e-02,
       5.41680008e-02, 6.57460019e-02, 7.83950016e-02, 8.32460001e-02,
       9.05809999e-02, 9.17439982e-02, 1.31246001e-01, 2.57362008e-01,
       0.00000000e+00, 0.00000000e+00, 3.06000004e+01, 1.77999992e+01,
       5.32352482e-04, 1.16365456e+02, 4.70286714e+00, 1.30000000e+01,
       1.80000000e+02, 3.68146968e+01, 1.32203519e+00]), array([4.00000000e+01, 4.90000000e+01, 1.62000008e+01, 3.00000000e+00,
       7.19999981e+00, 0.00000000e+00, 2.07000008e+01, 4.70849983e-02,
       5.41680008e-02, 6.57460019e-02, 7.83950016e-02, 8.32460001e-02,
       9.05809999e-02, 9.17439982e-02, 1.31246001e-01, 2.57362008e-01,
       3.06000004e+01, 1.77999992e+01, 1.30000000e+01, 1.32203519e+00]), tensor([[40.,  6.

In [31]:
class Partial_QNetwork(nn.Module):
    """Agent (Policy) Model."""
    # given a state of 35 dim, Qnetwork will return 200 values for each possible action  

    def __init__(self, state_size, action_size, fc1_units=128*2,fc2_units=128*2,fc3_units=128*2):
        """Initialize parameters and build model.
        Params
        ======
            state_size (int): Dimension of each state
            action_size (int): Dimension of each action
            fc1_units (int): Number of nodes in first hidden layer
            why is it 256? randomly?
        """
        super(Partial_QNetwork, self).__init__()
        self.fc1 = nn.Linear(state_size, fc1_units)
        self.fc2 = nn.Linear(fc1_units, fc2_units)
        self.fc3 = nn.Linear(fc2_units, fc3_units)
        self.fc4 = nn.Linear(fc3_units, action_size)
        # set a nn with 1 layer
        
    def forward(self, state):
        """Build a network that maps state -> action values."""
        x = F.relu(self.fc1(state))
        y = F.relu(self.fc2(x))
        z = F.relu(self.fc3(y))
        #Applies the rectified linear unit function element-wise. max(0,x)
        return 4*torch.sigmoid(self.fc4(z))*torch.tensor([[float(40),float(6)]])

In [32]:
qnetwork = Partial_QNetwork(20, 2)

In [47]:
sample=random.sample(fix_memory,5)
input1=sample[0][2]
#print(input1)
state=torch.from_numpy(sample[0][1]).float().unsqueeze(0)
input2=qnetwork(state)
input2=input2.type(torch.float64)
for i in range(1,5):
        input1=torch.vstack((input1,sample[i][2]))
        state=torch.from_numpy(sample[i][1]).float().unsqueeze(0).to(device)
        v=qnetwork(state)
        v=v.type(torch.float64)
        input2=torch.vstack((input2,v))
print(input1)
print(input2)

tensor([[ 0.,  6.],
        [40.,  6.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]], dtype=torch.float64)
tensor([[10.4779, 13.6906],
        [39.1274, 12.7955],
        [86.6090, 14.7945],
        [77.3985, 11.7061],
        [13.0372, 13.9259]], dtype=torch.float64, grad_fn=<CatBackward0>)


In [7]:
a=torch.tensor([[1,2]])
b=torch.tensor([[3,4]])
c=torch.vstack((a,b))
print(c)

tensor([[1, 2],
        [3, 4]])


In [8]:
a=torch.tensor([[1,2]])
b=torch.tensor([[3,4]])
d=torch.vstack((b,a))

In [11]:
c=torch.vstack((c,c))
d=torch.vstack((d,d))
c=c.type(torch.float64)
d=d.type(torch.float64)
print(c)
print(d)
print(F.mse_loss(c,d))

tensor([[1., 2.],
        [3., 4.],
        [1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[3., 4.],
        [1., 2.],
        [3., 4.],
        [1., 2.]], dtype=torch.float64)
tensor(4., dtype=torch.float64)
